### ISSUE TITLE
accum_channels renaming results in channel deletion

### ISSUE THREAD

**Issue by AUdaltsova** [openclimatefix/ocf_datapipes#358]
## Describe the bug
When using nwp_accum_channels feature the accum_channels end up not being saved to the resulting batch. I think it happens because the channels are renamed after diffing, and at normalisation they get discarded as means and stds do not have values for prefixed channel names

## To Reproduce
This is the config I used:
```
    ecmwf:
      nwp_provider: ecmwf
      # Path to ECMWF NWP data in zarr format
      # n.b. It is not necessary to use multiple or any NWP data. These entries can be removed
      nwp_zarr_path: /mnt/storage_b/nwp/ecmwf/india/*zarr.zip
      history_minutes: 60
      forecast_minutes: 480 # 8 hours
      time_resolution_minutes: 60
      nwp_channels:
        - t2m # 2-metre temperature
        - dswrf # downwards short-wave radiation flux, these are missing in new ECMWF data?
        - dlwrf # downwards long-wave radiation flux, these are missing in new ECMWF data?
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - tcc # total cloud cover
        - sde # snow depth water equivalent
        - sr # direct solar radiation
        - duvrs # downwards UV radiation at surface
        # - prate # precipitation rate
        - u10 # 10-metre U component of wind speed
        # - u100 # 100-metre U component of wind speed
        # - u200 # 200-metre U component of wind speed
        - v10 # 10-metre V component of wind speed
        # - v100 # 100-metre V component of wind speed
        # - v200 # 200-metre V component of wind speed
      nwp_accum_channels:
        - dswrf # downwards short-wave radiation flux, these are missing in new ECMWF data?
        - dlwrf # downwards long-wave radiation flux, these are missing in new ECMWF data?
        - sr # direct solar radiation
        - duvrs # downwards UV radiation at surface
      nwp_image_size_pixels_height: 4
      nwp_image_size_pixels_width: 4
      dropout_timedeltas_minutes: [-360]
      dropout_fraction: 1.0
      max_staleness_minutes: null
```

resulting batches have channel list of ['t2m' 'hcc' 'mcc' 'lcc' 'tcc' 'sde' 'u10' 'v10'] i e without the differ channels

When I put in debugging prints into ocf_datapipes/transform/xarray/normalize.py it's visible that the data gets into the function with the full channel range, including prefixed differ channels, but after normalisation those channels disappear:

```
xr_dataset: <xarray.DataArray 'ECMWF_India' (target_time_utc: 10, channel: 12, latitude: 4,
                                 longitude: 4)>
dask.array<getitem, shape=(10, 12, 4, 4), dtype=float32, chunksize=(10, 1, 4, 4), chunktype=numpy.ndarray>
Coordinates:
    init_time_utc    (target_time_utc) datetime64[ns] 2023-09-07 ... 2023-09-07
  * latitude         (latitude) float64 14.2 14.1 14.0 13.9
  * longitude        (longitude) float64 78.2 78.3 78.4 78.5
    step             (target_time_utc) timedelta64[ns] 07:00:00 ... 16:00:00
  * channel          (channel) <U10 't2m' 'diff_dswrf' ... 'u10' 'v10'
  * target_time_utc  (target_time_utc) datetime64[ns] 2023-09-07T07:00:00 ......
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    institution:             European Centre for Medium-Range Weather Forecasts
    t0_idx:                  1
    sample_period_duration:  1:00:00 

means <xarray.DataArray (channel: 17)>
array([ 5.6931292e+07,  3.1114434e+07,  3.3634428e+06,  2.6409385e-01,
        9.5489569e-02,  1.1118798e-01,  3.0280227e-05,  1.5021927e-03,
        3.1403020e+07,  2.9824463e+02,  3.3420485e-01,  7.7551073e-01,
        1.0605329e+00,  1.2298915e+00,  2.3328656e-02, -7.5774267e-02,
       -1.2550499e-01], dtype=float32)
Coordinates:
  * channel  (channel) <U5 'dlwrf' 'dswrf' 'duvrs' 'hcc' ... 'v10' 'v100' 'v200' 

stds: <xarray.DataArray (channel: 17)>
array([3.4551808e+07, 2.1211150e+07, 2.3002055e+06, 3.9427227e-01,
       2.2802404e-01, 2.2542898e-01, 2.3954990e-04, 9.0431899e-02,
       2.3481620e+07, 7.5743079e+00, 4.0463716e-01, 2.7440550e+00,
       4.0843625e+00, 4.7704511e+00, 2.4011586e+00, 3.5278924e+00,
       3.9741590e+00], dtype=float32)
Coordinates:
  * channel  (channel) <U5 'dlwrf' 'dswrf' 'duvrs' 'hcc' ... 'v10' 'v100' 'v200'
 
normalised xr_data: <xarray.DataArray (target_time_utc: 10, channel: 8, latitude: 4, longitude: 4)>
dask.array<truediv, shape=(10, 8, 4, 4), dtype=float32, chunksize=(10, 1, 4, 4), chunktype=numpy.ndarray>
Coordinates:
  * latitude         (latitude) float64 14.2 14.1 14.0 13.9
  * longitude        (longitude) float64 78.2 78.3 78.4 78.5
  * channel          (channel) <U10 't2m' 'hcc' 'mcc' ... 'sde' 'u10' 'v10'
  * target_time_utc  (target_time_utc) datetime64[ns] 2023-09-07T07:00:00 ......
    init_time_utc    (target_time_utc) datetime64[ns] 2023-09-07 ... 2023-09-07
    step             (target_time_utc) timedelta64[ns] 07:00:00 ... 16:00:00
Attributes:
    Conventions:             CF-1.7
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    institution:             European Centre for Medium-Range Weather Forecasts
    t0_idx:                  1
    sample_period_duration:  1:00:00

```

## Proposed solution

There might be something important about prefixing differ channels that I'm missing, but if not, I think the names should be left as is. I think we assume the constants we keep are for non-accum data?

Also maybe add a check that all channels have consts assigned to them/channel list is the same before saving?
