### ISSUE TITLE
Load multile PV datasets and join

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/ocf_datapipes#82]
Current data pipelines only load one pv set of files.

Would be good to load multiple pv files. 

For exmaple the config could be
```
pv:
    pv_files_groups:
      - label: solar_sheffield_passiv
        pv_filename: experiments/003/Italy_PV_timeseries_batch.netcdf
        pv_metadata_filename: experiments/003/PVOutput_Italy_systems_metadata.csv
      - label: SV
        pv_filename: experiments/003/SV_Italy_PV_timeseries_batch.netcdf
        pv_metadata_filename: experiments/003/SV_Italy_systems_metadata.csv
    get_center: false
    pv_image_size_meters_height: 100
    pv_image_size_meters_width: 100
    n_pv_systems_per_example: 1
    history_minutes: 240
    forecast_minutes: 240
    start_datetime: 2021-01-01 00:00
    end_datetime: 2022-10-01 00:00
    time_resolution_minutes: 15
```

One idea could be to pass `PV` model object into 'OpenPVFromNetCDFIterDataPipe' and then inside there it loops over the `pv_files_grpups` and joins them together
